### ISSUE TITLE
Dead

### ISSUE THREAD

**Issue by ThePLROutlet** [szr2001/WorkLifeBalance#1]
Well the idea is great but it won't open.

**Comment by szr2001** [comment]
Try running it as administrator, the app needs admin rights to be able to read the foreground windows and processes, it should have automatically restarted itself and request admin right if you opened without it.
if nothing works then look in the app folder for a Logs folder, if anything happened it must be logged there and provide me with the latest log file.
Also remember to extract the archive first if you didn't already, if not it can cause this problem, and move the folder in a place where you would want it to be, i should probably make it into an installer.
And its Windows only.

**Comment by szr2001** [comment]
Also remember to extract the archive first if you didn't already, if not it can cause this problem.

**Comment by ThePLROutlet** [comment]
Subject: Regarding Your App and Possible Collaboration

Hi Robert,

Thank you for your prompt response. In response to your query, I followed
your instructions meticulously and tested everything. Unfortunately, I must
admit my disappointment, as I genuinely believe that if anyone could
benefit from an app of this nature, it would be me.

Considering the capabilities of my system (Windows 11 Pro, Legion T5 with
64GB RAM, and 8 terabytes of memory), resource constraints should not be an
issue. I also have access to Linux, though I haven't attempted it there
yet, uncertain if it's compatible.

I wonder if there might be an alternative way to make it work. Given my
demanding work hours, which my wife would describe as "atrocious," I
desperately need an application with these features. My recent visit to
your website was driven by the demands of my new business, where I find
myself wearing many hats.

Pardon my tangent; I hope you don't mind me bouncing this off you. I've
compiled detailed instructions outlining precisely what I require, and it
was this that led me to your site. Recognizing your coding skills, I'd
appreciate the opportunity to discuss whether you might be interested in
assisting. I'm looking for someone proficient in coding and familiar with
WordPress, which I find straightforward but time-consuming.

My primary goal is to find someone who can follow these detailed
instructions and integrate artificial intelligence applications onto a
webpage. Is this something you'd consider discussing further? While I'm not
generating income at the moment, I believe we could reach an arrangement
that benefits us both. Please let me know your thoughts on both matters.

All the best friend,

JVM POWER STUDIOS INC/
MYWEBSITY
John Mendez
CEO
Office: 954-357-3728
Direct: 786-548-2257

**Comment by szr2001** [comment]
Sadly I have no experience in building webpages and little experience with artificial intelligence so I'm not sure if I would be of much service, though I could try to fix the problem you are facing with my app, though for me to try to debug and see what the problem might be I will require the file that the app generates inside the WorkLifeBalance/Logs folder where the app writes everything that is doing at runtime and if it has problems starting it must be written there what it is in more details so I might get an idea on what the problem might be.

**Comment by szr2001** [comment]
Now if I start to think more about it, if you are using an antivirus, the antivirus might delete some of the files and make it unable to start, because the app has code to get the background processes so it can record how much time you spent on them, so it might get flagged as a virus and deleted by the antivirus.

**Comment by ThePLROutlet** [comment]
Robert I don't believe that is the case. I would receive a request as to
what to do about the warning.You made mention of that possibility in the
app. Let's set up a remote session. Where are you located? Fla??
Best Regards,
JVM POWER STUDIOS INC/
MYWEBSITY
John Mendez
CEO
Office: 954-357-3728
Direct: 786-548-2257

**Comment by szr2001** [comment]
I live in Romania.
We could use Team Viewer and I will try to inspect and figure out what exactly is wrong with the app.
It must be something specific with the computer or some missing dll files because I did request a friend of mine to try the app and it did work with no problems so it must be something specific to your device.

**Comment by ThePLROutlet** [comment]
Ok, sounds good. Do you have Microsoft teams?
Best Regards,
JVM POWER STUDIOS INC/
MYWEBSITY
John Mendez
CEO
Office: 954-357-3728
Direct: 786-548-2257

**Comment by szr2001** [comment]
The new app version has been released, it might have solved the start-up problem on your device. 
It also has a ton of new features
You could give it a try
https://roberbot.itch.io/work-life-balance

Hopefully it will now work on your machine.
